<?php

namespace Prestamo\PrestamoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MunicipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipioRepository extends EntityRepository
{
}