<?php

namespace Prestamo\PrestamoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaRepository extends EntityRepository
{
    public function findTodasPersonas()
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT p FROM Prestamo\PrestamoBundle\Entity\Persona p
                                    ORDER BY p.nombre ASC')
                    ->getResult();
    }
}