<?php

namespace Prestamo\PrestamoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrestamoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestamoRepository extends EntityRepository
{
    public function findTodosPrestamos()
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT p FROM Prestamo\PrestamoBundle\Entity\Prestamo p ')
                    ->getResult();
    }
}